// <auto-generated />
using Lynx.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lynx.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240901072905_AddNewTenant")]
    partial class AddNewTenant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lynx.Core.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "GlobalTech"
                        },
                        new
                        {
                            Id = 2,
                            Name = "BlueSkyTech"
                        },
                        new
                        {
                            Id = 3,
                            Name = "AlphaIndustries"
                        },
                        new
                        {
                            Id = 4,
                            Name = "TechGiant"
                        },
                        new
                        {
                            Id = 5,
                            Name = "New Client"
                        });
                });

            modelBuilder.Entity("Lynx.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Alice@gmailcom",
                            FirstName = "Alice",
                            LastName = "john",
                            Password = "testafs",
                            TenantId = 1,
                            UserName = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Bob@gmailcom",
                            FirstName = "Bob",
                            LastName = "Hanks",
                            Password = "asdf",
                            TenantId = 2,
                            UserName = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Tom@gmailcom",
                            FirstName = "Tom",
                            LastName = "teves",
                            Password = "asdfa",
                            TenantId = 1,
                            UserName = "Tom"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Leonardo@gmailcom",
                            FirstName = "Leonardo",
                            LastName = "john",
                            Password = "asfasf",
                            TenantId = 1,
                            UserName = "Leonardo"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Brian@gmailcom",
                            FirstName = "Brian",
                            LastName = "Hanks",
                            Password = "sdfas",
                            TenantId = 2,
                            UserName = "Brian"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
